-- Supabase SQL Schema for Link Whitelist System
-- Copy and paste this into Supabase SQL Editor

-- Create the allowed_links table for storing whitelisted links per group
CREATE TABLE IF NOT EXISTS allowed_links (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  group_id TEXT NOT NULL,
  url TEXT NOT NULL,
  added_by TEXT NOT NULL,
  description TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  
  -- Composite unique constraint to prevent duplicate links in same group
  UNIQUE(group_id, url)
);

-- Create indexes for faster lookups
CREATE INDEX IF NOT EXISTS idx_allowed_links_group_id ON allowed_links(group_id);
CREATE INDEX IF NOT EXISTS idx_allowed_links_url ON allowed_links(url);
CREATE INDEX IF NOT EXISTS idx_allowed_links_group_url ON allowed_links(group_id, url);

-- Enable row-level security if you want (optional)
ALTER TABLE allowed_links ENABLE ROW LEVEL SECURITY;

-- Create the link_warnings table to track link violations
CREATE TABLE IF NOT EXISTS link_warnings (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  group_id TEXT NOT NULL,
  user_id TEXT NOT NULL,
  link_sent TEXT NOT NULL,
  warned_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  reason TEXT DEFAULT 'Unapproved link shared'
);

-- Create indexes for link_warnings
CREATE INDEX IF NOT EXISTS idx_link_warnings_group_id ON link_warnings(group_id);
CREATE INDEX IF NOT EXISTS idx_link_warnings_user_id ON link_warnings(user_id);
CREATE INDEX IF NOT EXISTS idx_link_warnings_group_user ON link_warnings(group_id, user_id);

-- Sample data (optional - delete later)
-- INSERT INTO allowed_links (group_id, url, added_by, description) 
-- VALUES ('123456-7890@g.us', 'https://www.youtube.com', '1234567890@s.whatsapp.net', 'YouTube official');
