-- Supabase SQL Schema for Warning System
-- Copy and paste this into Supabase SQL Editor to set up the warnings table

-- Create the warnings table
CREATE TABLE IF NOT EXISTS warnings (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  group_id TEXT NOT NULL,
  user_id TEXT NOT NULL,
  warn_count INT DEFAULT 1,
  last_warned_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  last_reason TEXT DEFAULT 'No reason provided',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  
  -- Composite unique constraint to prevent duplicate entries
  UNIQUE(group_id, user_id)
);

-- Create an index for faster lookups
CREATE INDEX IF NOT EXISTS idx_warnings_group_id ON warnings(group_id);
CREATE INDEX IF NOT EXISTS idx_warnings_user_id ON warnings(user_id);
CREATE INDEX IF NOT EXISTS idx_warnings_group_user ON warnings(group_id, user_id);

-- Add row-level security if you want (optional)
ALTER TABLE warnings ENABLE ROW LEVEL SECURITY;

-- Insert sample data for testing (optional - delete later)
-- INSERT INTO warnings (group_id, user_id, warn_count, last_reason) 
-- VALUES ('123456-7890@g.us', '1234567890@s.whatsapp.net', 1, 'Spamming messages');
